name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2HOST }}
          username: ${{ secrets.EC2USER }}
          key: ${{ secrets.EC2SSHKEY }}
          script: |
            cd ${{ secrets.EC2_APP_PATH }}
            git reset --hard
            git pull origin main
            npm install
            pm2 restart worksphere-backend
