name: Deploy Full Stack to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2HOST }}
          username: ${{ secrets.EC2USER }}
          key: ${{ secrets.EC2SSHKEY }}
          script: |
            # Navigate to backend
            cd ${{ secrets.EC2_APP_PATH }}

            # Pull latest code
            git reset --hard
            git pull origin main

            # Install backend dependencies
            npm install

            # Navigate to frontend
            cd ..

            # Install frontend dependencies (optional if already installed)
            npm install

            # Build React frontend (generates dist folder)
            npm run build

            # Go back to backend folder
            cd ./backend

            # Restart backend with PM2
            pm2 restart codveda-app


